### Rota raiz

GET http://localhost:8080/api

### Listar todos os usuários

GET http://localhost:8080/api/usuarios

### Criar um usuário

POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "email": "joao@email.com",
    "senha": "123456"
}

### Buscar usuário por ID

GET http://localhost:8080/api/usuarios/[ID_USUARIO]

### Atualizar um usuário

PUT http://localhost:8080/api/usuarios/?id=[ID_USUARIO]
Content-Type: application/json

{
    "email": "joao.novo@email.com",
    "senha": "novaSenha"
}

### Deletar um usuário

DELETE http://localhost:8080/api/usuarios/?id=[ID_USUARIO]
