### Rota raiz

GET http://localhost:8080/api

### Autentica

POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "newton@gmail.com",
    "senha": "changeit"
}

### Listar todos os usuários

GET http://localhost:8080/api/usuarios

### Criar um usuário

POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "email": "newton@gmail.com",
    "senha": "changeit"
}

### Buscar usuário por ID

GET http://localhost:8080/api/usuarios/[ID_USUARIO]

### Atualizar um usuário

PUT http://localhost:8080/api/usuarios/?id=3
Content-Type: application/json

{
    "email": "tesla@gmail.com",
    "senha": "changeit"
}

### Deletar um usuário

DELETE http://localhost:8080/api/usuarios/?id=[ID_USUARIO]
