### Rota raiz

GET http://localhost:8080/

###

### Listar todos os usuários

GET http://localhost:8080/usuarios

###

### Buscar usuário por ID

GET http://localhost:8080/usuarios/[ID_USUARIO]

###

### Criar um usuário

POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "email": "joao@email.com",
    "senha": "123456"
}

###

### Atualizar um usuário

PUT http://localhost:8080/usuarios/?id=[ID_USUARIO]
Content-Type: application/json

{
    "email": "joao.novo@email.com",
    "senha": "novaSenha"
}

###

### Deletar um usuário

DELETE http://localhost:8080/usuarios/?id=[ID_USUARIO]
